version: "3.8"

services:
  common:
    ports:
      - 3003:3003
    build:
      context: common
      dockerfile: ./Dockerfile
    command: sh -c "npm run build && npm run dev"
    # command: tail -f /dev/null
    volumes:
      - ./common:/home/node/common
      # - common-files:/home/node/common
      - node-modules:/home/node/node_modules
  gpa:
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: gpa/Dockerfile
    # command: tail -f /dev/null
    command: sh -c "npm run build && npm run dev"
    volumes:
      - ./gpa:/home/node/gpa
      # TODO change context to gpa and adjust accordingly and this when we don't need hot reload for common
      # - common-files:/home/node/common
      - ./common:/home/node/common
      - node-modules:/home/node/node_modules
      - /home/node/gpa/.next
    depends_on:
      - common
  # spe:
  #   ports:
  #     - 3001:3001
  #   build:
  #     context: .
  #     dockerfile: spe/Dockerfile
  #   command: sh -c "npm run build && npm run dev"
  #   volumes:
  #     - ./spe:/home/node/spe
  #     # TODO change context to gpa and adjust accordingly and this when we don't need hot reload for common
  #     # - common-files:/home/node/common
  #     - ./common:/home/node/common
  #     - node-modules:/home/node/node_modules
  #     - /home/node/spe/.next
  #   depends_on:
  #     - common
  # pms:
  #   ports:
  #     - 3002:3002
  #   build:
  #     context: .
  #     dockerfile: pms/Dockerfile
  #   # command: tail -f /dev/null
  #   command: sh -c "npm run build && npm run dev"
  #   volumes:
  #     - ./pms:/home/node/pms
  #     # TODO change context to gpa and adjust accordingly and this when we don't need hot reload for common
  #     # - common-files:/home/node/common
  #     - ./common:/home/node/common
  #     - node-modules:/home/node/node_modules
  #     - /home/node/pms/.next
  #   depends_on:
  #     - common
volumes:
  # common-files:
  node-modules:
