version: "3.8"

services:
  gpa:
    ports:
      - 3000:3000
    build:
      context: gpa
      dockerfile: ./Dockerfile
    volumes:
      - ./gpa:/home/node/gpa
      - /home/node/gpa//node_modules
      - /home/node/gpa/.next
    depends_on:
      - db
  spe:
    ports:
      - 3001:3001
    build:
      context: spe
      dockerfile: ./Dockerfile
    volumes:
      - ./spe:/home/node/spe
      - /home/node/spe//node_modules
      - /home/node/spe/.next
  db:
    image: postgres
    env_file: .env
    volumes:
      - ./db/data/postgres:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    env_file: .env
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"
    depends_on:
      - db
volumes:
  pgadmin-data:
