version: "3.8"

services:
  common:
    build:
      context: common
      dockerfile: ./Dockerfile
    # command: tail -f /dev/null
    volumes:
      # - ./common:/home/node/common
      - common-files:/home/node/common
      - node-modules:/home/node/node_modules
  gpa:
    ports:
      - 3000:3000
    build:
      context: gpa
      dockerfile: ./Dockerfile
    # command: tail -f /dev/null
    command: sh -c "npm run build && npm run dev"
    volumes:
      - ./gpa:/home/node/gpa
      - common-files:/home/node/common
      - node-modules:/home/node/node_modules
      - /home/node/gpa/.next
    depends_on:
      - common
      - db
  # spe:
  #   ports:
  #     - 3001:3001
  #   build:
  #     context: spe
  #     dockerfile: ./Dockerfile
  #   volumes:
  #     - ./spe:/home/node/spe
  #     - /home/node//node_modules
  #     - /home/node/spe/.next
  #   depends_on:
  #     - common
  # pms:
  #   ports:
  #     - 3002:3002
  #   build:
  #     context: pms
  #     dockerfile: ./Dockerfile
  #   # command: tail -f /dev/null
  #   command: sh -c "npm run build && npm run dev"
  #   volumes:
  #     - ./pms:/home/node/pms
  #     - common-files:/home/node/common
  #     - node-modules:/home/node/node_modules
  #     - /home/node/pms/.next
  #   depends_on:
  #     - common
  #     - db
  db:
    image: postgres
    env_file: .env
    volumes:
      - ./db/data/postgres:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    env_file: .env
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"
    depends_on:
      - db
volumes:
  pgadmin-data:
  common-files:
  node-modules:
