/**
 * Generated by the artifact generator [@inrupt/artifact-generator], version [2.0.0]
 * as part of artifact: [generated-vocab-solidhotel], version: [0.0.1]
 * on 'Sunday, July 17, 2022 11:54 PM'.
 *
 * Vocabulary built from input: [../solidhotel.ttl].
 * The generator detected the following terms in the source vocabulary:
 *  - Classes: [5]
 *  - Properties: [8]
 *  - Literals: [0]
 *  - Constant IRIs: [0]
 *  - Constant strings: [0]
 *
 * The ontology adding RDF terms required for the Solid Hotel project.
 */

// We prefix our local variables with underscores to (hopefully!) prevent
// potential names clashes with terms from vocabularies.
const _NAMESPACE = "https://github.com/gergelyth/solid-hotel/blob/master/solidhotel.ttl#";
function _NS (localName) {
  return (_NAMESPACE + localName);
}

/**
 * The ontology adding RDF terms required for the Solid Hotel project.
 */
const SOLIDHOTEL = {
  PREFIX: "solidhotel",
  NAMESPACE: _NAMESPACE,
  PREFIX_AND_NAMESPACE: { "solidhotel": "https://github.com/gergelyth/solid-hotel/blob/master/solidhotel.ttl#" },
  NS: _NS,

  // *****************
  // All the Classes.
  // *****************

  /**
   * A resource containing information which helps to pair Solid Pods to reservations.
   *
   * This term provides descriptions only in English.
   */
  ReservationLink: _NS("ReservationLink"),

  /**
   * A resource helping to identify what personal information fields are kept at the hotel.
   *
   * This term has [2] labels and comments, in the languages [NoLocale, en].
   */
  PrivacyToken: _NS("PrivacyToken"),

  /**
   * Enumerated type values for a Notification.
   *
   * This term provides descriptions only with no explicit locale.
   */
  NotificationType: _NS("NotificationType"),

  /**
   * A resource containing information about the deletion request of a privacy token.
   *
   * This term has [2] labels and comments, in the languages [NoLocale, en].
   */
  PrivacyTokenDeletion: _NS("PrivacyTokenDeletion"),

  /**
   * A resource containing information about a reservation state change.
   *
   * This term has [2] labels and comments, in the languages [NoLocale, en].
   */
  ReservationStateChange: _NS("ReservationStateChange"),


  // *******************
  // All the Properties.
  // *******************

  /**
   * Defines if the subject has been processed already.
   *
   * This term provides descriptions only in English.
   */
  isProcessed: _NS("isProcessed"),

  /**
   * Defines the type of the notification
   *
   * This term provides descriptions only in English.
   */
  notificationType: _NS("notificationType"),

  /**
   * Defines the identification document type of the person.
   *
   * This term provides descriptions only in English.
   */
  idDocumentType: _NS("idDocumentType"),

  /**
   * Defines the identification document number of the person.
   *
   * This term provides descriptions only in English.
   */
  idDocumentNumber: _NS("idDocumentNumber"),

  /**
   * Refers to the target Solid dataset.
   *
   * This term provides descriptions only in English.
   */
  targetDataset: _NS("targetDataset"),

  /**
   * Refers to the target hotel of the dataset.
   *
   * This term provides descriptions only in English.
   */
  forHotel: _NS("forHotel"),

  /**
   * Refers to the target reservation in the Solid Pod.
   *
   * This term provides descriptions only in English.
   */
  forReservation: _NS("forReservation"),

  /**
   * The array of the personal information fields targeted by this resource.
   *
   * This term provides descriptions only in English.
   */
  targetFields: _NS("targetFields"),

}

module.exports = SOLIDHOTEL;
